export type VendorEventFormat = "in-person" | "virtual" | "hybrid";
export type VendorEventStatus = "confirmed" | "check-source";

export interface VendorEvent {
  id: string;
  name: string;
  dateLabel: string;
  sortDate: string;
  format: VendorEventFormat;
  location?: string;
  description: string;
  status: VendorEventStatus;
  sourceUrl: string;
  sourceLabel: string;
}

export interface VendorGroup {
  id: string;
  company: string;
  category: string;
  homepageUrl: string;
  events: VendorEvent[];
  /** Shown when a company has no confirmed dated events in the research window. */
  watchNote?: string;
}

/**
 * RAG / vector database / GraphRAG vendor events — competitive & partnership
 * tracking. Researched 2026-07-16 against each vendor's own events page.
 * These are companies HydraDB competes or overlaps with, not events for
 * agent builders generally (see events.ts for that).
 */
export const vendorGroups: VendorGroup[] = [
  {
    id: "pinecone",
    company: "Pinecone",
    category: "Vector database",
    homepageUrl: "https://www.pinecone.io/community/events/",
    events: [
      {
        id: "pinecone-hands-on-intro",
        name: "Vector Search for Agentic AI: Hands-on Intro",
        dateLabel: "Jul 23 · Aug 20 · Sep 17 · Oct 22 · Nov 12",
        sortDate: "2026-07-23",
        format: "virtual",
        description: "Recurring intro webinar on hybrid/semantic search and RAG with Pinecone.",
        status: "confirmed",
        sourceUrl: "https://www.pinecone.io/community/events/",
        sourceLabel: "pinecone.io",
      },
      {
        id: "pinecone-burn-less-tokens",
        name: "Burn Less Tokens Meetup",
        dateLabel: "Jul 28",
        sortDate: "2026-07-28",
        format: "in-person",
        location: "New York, NY",
        description: "Pinecone-hosted meetup on token-efficient agentic AI.",
        status: "confirmed",
        sourceUrl: "https://luma.com/pinecone",
        sourceLabel: "luma.com/pinecone",
      },
      {
        id: "pinecone-la-agentic",
        name: "LA Agentic AI Meetup hosted by Pinecone",
        dateLabel: "Aug 11",
        sortDate: "2026-08-11",
        format: "in-person",
        location: "Los Angeles, CA",
        description: "Community meetup on agentic AI, hosted by Pinecone.",
        status: "confirmed",
        sourceUrl: "https://luma.com/pinecone",
        sourceLabel: "luma.com/pinecone",
      },
      {
        id: "pinecone-access-control",
        name: "Deep Dive: Access Control",
        dateLabel: "Aug 12",
        sortDate: "2026-08-12",
        format: "virtual",
        description: "Product deep-dive webinar on Pinecone's access control features.",
        status: "confirmed",
        sourceUrl: "https://www.pinecone.io/community/events/",
        sourceLabel: "pinecone.io",
      },
    ],
  },
  {
    id: "neo4j",
    company: "Neo4j",
    category: "Graph database (GraphRAG)",
    homepageUrl: "https://neo4j.com/events/",
    events: [
      {
        id: "neo4j-graphtalk-sf",
        name: "GraphTalk San Francisco",
        dateLabel: "Jul 23",
        sortDate: "2026-07-23",
        format: "in-person",
        location: "San Francisco, CA",
        description: '"Graph technology reshaping industries" community talk.',
        status: "confirmed",
        sourceUrl: "https://neo4j.com/events/",
        sourceLabel: "neo4j.com",
      },
      {
        id: "neo4j-enterprise-ai-knowledge-layer",
        name: "Enterprise AI Knowledge Layer",
        dateLabel: "Jul 21",
        sortDate: "2026-07-21",
        format: "virtual",
        description: "Regional webinar sessions (APAC/EU/Americas) on a knowledge-layer approach to AI with Neo4j.",
        status: "confirmed",
        sourceUrl: "https://neo4j.com/events/",
        sourceLabel: "neo4j.com",
      },
      {
        id: "neo4j-graphsummit-nyc",
        name: "GraphSummit NYC",
        dateLabel: "Sep 4–5 (sources conflict — confirm exact date)",
        sortDate: "2026-09-04",
        format: "in-person",
        location: "New York, NY",
        description: "Flagship regional GraphRAG/AI-ready-data conference, part of the GraphSummit 2026 world tour.",
        status: "check-source",
        sourceUrl: "https://neo4j.com/graphsummit/",
        sourceLabel: "neo4j.com/graphsummit",
      },
      {
        id: "neo4j-graphsummit-london",
        name: "GraphSummit London",
        dateLabel: "2026, exact date TBA",
        sortDate: "2026-10-01",
        format: "in-person",
        location: "London",
        description: '"Build With Graph and GenAI" — part of the GraphSummit 2026 tour.',
        status: "check-source",
        sourceUrl: "https://neo4j.com/graphsummit/",
        sourceLabel: "neo4j.com/graphsummit",
      },
      {
        id: "neo4j-nodes-2026",
        name: "NODES 2026",
        dateLabel: "Nov 12",
        sortDate: "2026-11-12",
        format: "virtual",
        description: 'Neo4j\'s flagship 24-hour global developer conference — "Engineering Better Intelligence," with sessions on AI engineering, multi-agent workflows, and GraphRAG.',
        status: "confirmed",
        sourceUrl: "https://neo4j.com/nodes/",
        sourceLabel: "neo4j.com/nodes",
      },
    ],
  },
  {
    id: "langchain",
    company: "LangChain",
    category: "Orchestration framework",
    homepageUrl: "https://www.langchain.com/events",
    events: [
      {
        id: "langchain-interrupt-nyc",
        name: "Interrupt 2026 — NYC",
        dateLabel: "Sep 24",
        sortDate: "2026-09-24",
        format: "in-person",
        location: "Halo, Financial District, New York",
        description: "Flagship agent conference — East Coast leg (main SF edition already ran in May).",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
      {
        id: "langchain-interrupt-london",
        name: "Interrupt 2026 — London",
        dateLabel: "Oct 13",
        sortDate: "2026-10-13",
        format: "in-person",
        location: "Outernet, London",
        description: "Interrupt's European leg.",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
      {
        id: "langchain-sf-meetup",
        name: "LangChain SF Meetup — LLM Wikis / Agent Memory",
        dateLabel: "Jul 28",
        sortDate: "2026-07-28",
        format: "in-person",
        location: "San Francisco, CA",
        description: "Community meetup with an agent-memory focus — direct overlap with HydraDB's territory.",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
      {
        id: "langsmith-roadshow-silicon-valley",
        name: "LangSmith Roadshow — Silicon Valley",
        dateLabel: "Aug 27",
        sortDate: "2026-08-27",
        format: "in-person",
        location: "Silicon Valley, CA",
        description: "Product roadshow stop for LangSmith.",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
      {
        id: "langchain-ny-meetup",
        name: "LangChain NY Meetup — Building Agents with Agents",
        dateLabel: "Jul 21",
        sortDate: "2026-07-21",
        format: "in-person",
        location: "New York, NY",
        description: "Community meetup on meta/agent-building-agents patterns.",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
      {
        id: "langsmith-roadshow-atlanta",
        name: "LangSmith Roadshow — Atlanta",
        dateLabel: "Aug 11",
        sortDate: "2026-08-11",
        format: "in-person",
        location: "Atlanta, GA",
        description: "Product roadshow stop for LangSmith.",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
      {
        id: "langsmith-roadshow-boston",
        name: "LangSmith Roadshow — Boston",
        dateLabel: "Sep 29",
        sortDate: "2026-09-29",
        format: "in-person",
        location: "Boston, MA",
        description: "Product roadshow stop for LangSmith.",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
      {
        id: "langchain-world-summit-ai",
        name: "LangChain @ World Summit AI",
        dateLabel: "Oct 7",
        sortDate: "2026-10-07",
        format: "in-person",
        location: "Amsterdam",
        description: "LangChain presence at World Summit AI.",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
      {
        id: "langchain-reinvent",
        name: "LangChain @ AWS re:Invent",
        dateLabel: "Nov 30",
        sortDate: "2026-11-30",
        format: "in-person",
        location: "Las Vegas, NV",
        description: "LangChain presence at AWS re:Invent.",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
    ],
  },
  {
    id: "mongodb",
    company: "MongoDB",
    category: "Atlas Vector Search",
    homepageUrl: "https://www.mongodb.com/resources/directory/webinars",
    events: [
      {
        id: "mongodb-rag-emea",
        name: "AI Fundamentals — Part 2: RAG with MongoDB (EMEA)",
        dateLabel: "Jul 15, 10am BST",
        sortDate: "2026-07-15",
        format: "virtual",
        description: "RAG architecture, chunking, and retrievers with MongoDB.",
        status: "confirmed",
        sourceUrl: "https://www.mongodb.com/resources/directory/webinars",
        sourceLabel: "mongodb.com",
      },
      {
        id: "mongodb-vector-search-101",
        name: "Master AI Development — Vector Search Beginner to Pro",
        dateLabel: "Jul 22, 10am PT",
        sortDate: "2026-07-22",
        format: "virtual",
        description: "Semantic search with MongoDB Vector Search + Voyage AI embeddings.",
        status: "confirmed",
        sourceUrl: "https://www.mongodb.com/resources/directory/webinars",
        sourceLabel: "mongodb.com",
      },
      {
        id: "mongodb-agents-emea",
        name: "AI Fundamentals — Part 3: AI Agents (EMEA)",
        dateLabel: "Jul 22, 10am BST",
        sortDate: "2026-07-22",
        format: "virtual",
        description: "Tool use, memory, and agentic patterns on MongoDB.",
        status: "confirmed",
        sourceUrl: "https://www.mongodb.com/resources/directory/webinars",
        sourceLabel: "mongodb.com",
      },
      {
        id: "mongodb-atlas-confluent",
        name: "Agentic Apps on Real-Time Data — Atlas & Confluent",
        dateLabel: "Jul 23, 11am ET",
        sortDate: "2026-07-23",
        format: "virtual",
        description: "Atlas Vector Search + Confluent streaming for real-time agentic apps.",
        status: "confirmed",
        sourceUrl: "https://www.mongodb.com/resources/directory/webinars",
        sourceLabel: "mongodb.com",
      },
      {
        id: "mongodb-ai-system-design",
        name: "Master AI Development — AI System Design",
        dateLabel: "Jul 29, 10am PT",
        sortDate: "2026-07-29",
        format: "virtual",
        description: "Evaluation frameworks, retrieval strategy, and guardrails for production.",
        status: "confirmed",
        sourceUrl: "https://www.mongodb.com/resources/directory/webinars",
        sourceLabel: "mongodb.com",
      },
      {
        id: "mongodb-ai-coding",
        name: "Master AI Development — AI Coding with MongoDB",
        dateLabel: "Aug 4, 10am PT",
        sortDate: "2026-08-04",
        format: "virtual",
        description: "Agentic coding tools (incl. Claude Code) with the MongoDB MCP server.",
        status: "confirmed",
        sourceUrl: "https://www.mongodb.com/resources/directory/webinars",
        sourceLabel: "mongodb.com",
      },
    ],
    watchNote:
      "MongoDB.local's flagship regional conference series didn't have confirmed Jul–Dec city dates at research time — check mongodb.com/events directly.",
  },
  {
    id: "redis",
    company: "Redis",
    category: "Vector search / RAG",
    homepageUrl: "https://redis.io/events/",
    events: [
      {
        id: "redis-real-time-context-engine",
        name: "Real-time Context Engine: RAG, Memory & Agentic Infra",
        dateLabel: "Jul 30",
        sortDate: "2026-07-30",
        format: "virtual",
        description: "Webinar on RAG, agent memory, and agentic infrastructure using Redis — direct overlap with HydraDB's territory.",
        status: "confirmed",
        sourceUrl: "https://redis.io/events/",
        sourceLabel: "redis.io",
      },
    ],
  },
  {
    id: "zilliz",
    company: "Zilliz / Milvus",
    category: "Vector database",
    homepageUrl: "https://zilliz.com/event",
    events: [],
    watchNote:
      "The Unstructured Data Meetup series (Bay Area, Hangzhou, and other regions) and a \"Zilliz Cloud Live Demo\" webinar both appear to be active, but no confirmed Jul–Dec 2026 dates could be pulled from zilliz.com/event (JS-rendered page). Check zilliz.com/community/unstructured-data-meetup directly.",
  },
  {
    id: "qdrant",
    company: "Qdrant",
    category: "Vector database",
    homepageUrl: "https://qdrant.tech/community/",
    events: [],
    watchNote:
      "Qdrant's flagship Vector Space Day 2026 already ran Jun 11 in San Francisco — no second 2026 edition confirmed yet (last year's second leg was Berlin in September, so one may still land in this window). The biweekly \"Getting Started\" livestream continues but without specific forward dates. Check qdrant.tech/blog and qdrant.tech/community.",
  },
  {
    id: "weaviate",
    company: "Weaviate",
    category: "Vector database",
    homepageUrl: "https://weaviate.io/community/events",
    events: [],
    watchNote:
      "Weaviate's own events page showed no scheduled events at research time. SF and NYC meetup chapters exist but had no dated 2026 sessions listed. Check weaviate.io/community/events and meetup.com/Weaviate-San-Francisco.",
  },
  {
    id: "chroma",
    company: "Chroma",
    category: "Vector database",
    homepageUrl: "https://www.trychroma.com",
    events: [],
    watchNote:
      "No public events calendar found for Chroma at research time. Check trychroma.com and @trychroma on X directly.",
  },
  {
    id: "llamaindex",
    company: "LlamaIndex",
    category: "Orchestration framework",
    homepageUrl: "https://www.llamaindex.ai/blog",
    events: [],
    watchNote:
      "No confirmed dated Jul–Dec 2026 events found — LlamaIndex's most recent confirmed item was a Jun 30 webinar, just before this window. Their blog/newsletter is the primary events channel; check llamaindex.ai/blog monthly.",
  },
  {
    id: "elastic",
    company: "Elastic",
    category: "Vector search / RAG",
    homepageUrl: "https://events.elastic.co",
    events: [],
    watchNote:
      'An open-ended "Blogathon" community content campaign is running (not a single-date event). No single confirmed live event date found in-window — events.elastic.co blocked automated fetch, so a manual check will likely surface more.',
  },
];
