import type { Topic } from "./topics";

export type VendorEventFormat = "in-person" | "virtual" | "hybrid";
export type VendorEventStatus = "confirmed" | "check-source";

export interface VendorEvent {
  id: string;
  name: string;
  dateLabel: string;
  sortDate: string;
  format: VendorEventFormat;
  location?: string;
  description: string;
  status: VendorEventStatus;
  sourceUrl: string;
  sourceLabel: string;
  /** RAG / vector-DB / GraphRAG / agent-memory relevance — HydraDB pitch or inspiration fit. */
  topics?: Topic[];
}

export interface VendorGroup {
  id: string;
  company: string;
  category: string;
  homepageUrl: string;
  events: VendorEvent[];
  /** Shown when a company has no confirmed dated events in the research window. */
  watchNote?: string;
}

/**
 * RAG / vector database / GraphRAG vendor events — competitive & partnership
 * tracking. Researched 2026-08-13 against each vendor's own events page.
 * These are companies HydraDB competes or overlaps with, not events for
 * agent builders generally (see events.ts for that).
 */
export const vendorGroups: VendorGroup[] = [
  {
    id: "pinecone",
    company: "Pinecone",
    category: "Vector database",
    homepageUrl: "https://www.pinecone.io/community/events/",
    events: [
      {
        id: "pinecone-hands-on-intro",
        name: "Vector Search for Agentic AI: Hands-on Intro",
        dateLabel: "Aug 20 · Sep 17 · Oct 22 · Nov 12",
        sortDate: "2026-08-20",
        format: "virtual",
        description: "Recurring intro webinar on hybrid/semantic search and RAG with Pinecone.",
        status: "confirmed",
        sourceUrl: "https://www.pinecone.io/community/events/",
        sourceLabel: "pinecone.io",
        topics: ["vector-db", "rag", "agent-memory"],
      },
      {
        id: "pinecone-access-granted",
        name: "Access Granted: Enterprise Security with Pinecone",
        dateLabel: "Aug 19",
        sortDate: "2026-08-19",
        format: "virtual",
        description:
          "Product deep-dive webinar on Pinecone enterprise security / access control (listed as Access Granted on pinecone.io and luma.com/pinecone; previously titled Deep Dive: Access Control).",
        status: "confirmed",
        sourceUrl: "https://www.pinecone.io/community/events/",
        sourceLabel: "pinecone.io",
        topics: ["vector-db"],
      },
    ],
  },
  {
    id: "neo4j",
    company: "Neo4j",
    category: "Graph database (GraphRAG)",
    homepageUrl: "https://neo4j.com/events/",
    events: [
      {
        id: "neo4j-graphtalk-melbourne",
        name: "GraphTalk Melbourne: Building Production-Ready, Trustworthy AI",
        dateLabel: "Aug 20",
        sortDate: "2026-08-20",
        format: "in-person",
        location: "The George on Collins, Melbourne, Australia",
        description:
          "How a Neo4j knowledge graph keeps multiple AI agents aligned on shared business definitions — consistent, auditable answers across an AI stack.",
        status: "confirmed",
        sourceUrl:
          "https://neo4j.com/event/graphtalk-melbourne-building-production-ready-trustworthy-ai_20aug/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag", "agent-memory"],
      },
      {
        id: "neo4j-graphtalk-virtual-trustworthy-ai",
        name: "GraphTalk Virtual: Building Production-Ready, Trustworthy AI",
        dateLabel: "Aug 20",
        sortDate: "2026-08-20",
        format: "virtual",
        description:
          "Virtual GraphTalk with customer stories on productising AI with Neo4j knowledge graphs — paired with the Melbourne in-person GraphTalk.",
        status: "confirmed",
        sourceUrl:
          "https://neo4j.com/event/graphtalk-virtual-building-production-ready-trustworthy-ai_20aug/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag"],
      },
      {
        id: "neo4j-global-ai-construct-berlin",
        name: "Global AI Construct Berlin — Neo4j Mini Agentic Hack",
        dateLabel: "Aug 25",
        sortDate: "2026-08-25",
        format: "in-person",
        location: "Berlin, Germany",
        description:
          "Full-day hands-on build session on Neo4j, GraphRAG, agentic AI, and MCP — listed on neo4j.com/events.",
        status: "confirmed",
        sourceUrl: "https://neo4j.com/event/global-ai-construct-berlin/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag", "agent-memory"],
      },
      {
        id: "neo4j-karpathy-llm-wiki-graphrag",
        name: "Scale Karpathy’s LLM Wiki with Neo4j GraphRAG",
        dateLabel: "Aug 25",
        sortDate: "2026-08-25",
        format: "virtual",
        description:
          "Virtual session on turning Karpathy’s LLM Wiki pattern into a Neo4j GraphRAG knowledge layer for accurate, explainable retrieval — APAC/Europe timezone repeats also listed Aug 25 on neo4j.com/events.",
        status: "confirmed",
        sourceUrl:
          "https://neo4j.com/event/scale-karpathys-llm-wiki-with-neo4j-graphrag-aug-25/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag", "rag", "agent-memory"],
      },
      {
        id: "neo4j-tokyo-knowledge-design",
        name: "Knowledge Design in the AI Era — Tokyo",
        dateLabel: "Aug 26",
        sortDate: "2026-08-26",
        format: "in-person",
        location: "Tokyo, Japan",
        description:
          "Talk on modeling plant P&ID data as a Neo4j graph for knowledge design in industrial AI workflows.",
        status: "confirmed",
        sourceUrl: "https://neo4j.com/event/tokyo-knowledge-design-in-the-ai-era/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag"],
      },
      {
        id: "neo4j-foundry-workshop-atlanta",
        name: "AI Hands-On Workshop with Neo4j and Microsoft Foundry — Atlanta",
        dateLabel: "Aug 27",
        sortDate: "2026-08-27",
        format: "in-person",
        location: "Microsoft Atlantic Yards, Atlanta, GA",
        description:
          "Hands-on workshop pairing Neo4j graphs with Microsoft Foundry for AI application building.",
        status: "confirmed",
        sourceUrl:
          "https://neo4j.com/event/ai-hands-on-workshop-with-neo4j-and-microsoft-foundry-atlanta/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag"],
      },
      {
        id: "neo4j-genai-workshop-aws-boston",
        name: "Neo4j GenAI Hands-On Workshop with AWS — Boston",
        dateLabel: "Aug 27",
        sortDate: "2026-08-27",
        format: "in-person",
        location: "AWS Bos21, Boston, MA",
        description:
          "Half-day Graph Workshop with Neo4j and AWS on grounding generative AI in connected enterprise data.",
        status: "confirmed",
        sourceUrl: "https://neo4j.com/event/neo4j-genai-hands-on-workshop-with-aws-boston/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag"],
      },
      {
        id: "neo4j-pune-graphdb-meetup",
        name: "GraphDB User Group — Pune August Meetup",
        dateLabel: "Aug 29",
        sortDate: "2026-08-29",
        format: "in-person",
        location: "Pune, India",
        description: "Community meetup for engineers and practitioners working with graph databases.",
        status: "confirmed",
        sourceUrl: "https://neo4j.com/event/pune-graphdb-user-group-august-meetup/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag"],
      },
      {
        id: "neo4j-bengaluru-agentic-workshop",
        name: "Neo4j Agentic AI Workshop — Bengaluru Tech Week",
        dateLabel: "Sep 3",
        sortDate: "2026-09-03",
        format: "in-person",
        location: "Bengaluru, India",
        description:
          "Hands-on workshop building AI agents and tools with context graphs on Neo4j during Bengaluru Tech Week.",
        status: "confirmed",
        sourceUrl: "https://neo4j.com/event/neo4j-agentic-ai-workshop-at-bengaluru-tech-week/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag", "agent-memory"],
      },
      {
        id: "neo4j-graphtalk-singapore",
        name: "GraphTalk Singapore: Transforming Fraud Detection with Graph",
        dateLabel: "Sep 3",
        sortDate: "2026-09-03",
        format: "in-person",
        location: "33Club @ Raffles Place, Singapore",
        description:
          "In-person GraphTalk on graph-backed fraud detection — connected-data patterns for complex financial crime networks.",
        status: "confirmed",
        sourceUrl:
          "https://neo4j.com/event/graphtalk-singapore-transforming-fraud-detection-with-graph_sept-3/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag"],
      },
      {
        id: "neo4j-genai-fundamentals-sep3",
        name: "Neo4j & Generative AI Fundamentals — Hands-on Virtual Workshop",
        dateLabel: "Sep 3",
        sortDate: "2026-09-03",
        format: "virtual",
        description:
          "Virtual workshop for GenAI practitioners on elevating vector RAG with GraphRAG — knowledge-graph patterns for more accurate LLM outputs.",
        status: "confirmed",
        sourceUrl:
          "https://neo4j.com/event/neo4j-generative-ai-fundamentals-hands-on-virtual-workshop/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag", "rag"],
      },
      {
        id: "neo4j-agentsnexus-2026",
        name: "AgentsNexus 2026",
        dateLabel: "Sep 4–5",
        sortDate: "2026-09-04",
        format: "in-person",
        location: "India — venue TBA (confirm on neo4j.com/event/agentsnexus-2026)",
        description:
          "India-focused agentic-AI conference listed by Neo4j — developers and researchers on autonomous AI systems.",
        status: "check-source",
        sourceUrl: "https://neo4j.com/event/agentsnexus-2026/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag", "agent-memory"],
      },
      {
        id: "neo4j-agentcon-london",
        name: "AgentCon London 2026",
        dateLabel: "Sep 8",
        sortDate: "2026-09-08",
        format: "in-person",
        location: "London, UK — venue TBA (confirm on neo4j.com/event/agentcon-london-2026)",
        description:
          "One-day AI Agents World Tour stop for developers building with AI agents — listed on neo4j.com/events.",
        status: "check-source",
        sourceUrl: "https://neo4j.com/event/agentcon-london-2026/",
        sourceLabel: "neo4j.com",
      },
      {
        id: "neo4j-agntcon-mcpcon-japan",
        name: "AGNTCon + MCPCon Japan",
        dateLabel: "Sep 10–11",
        sortDate: "2026-09-10",
        format: "in-person",
        location: "Japan — venue TBA (confirm on neo4j.com/event/agntcon-mcpcon-japan)",
        description:
          "Agent + MCP conference Neo4j lists — agent architectures, infrastructure, and protocol tooling for the next wave of AI agents.",
        status: "check-source",
        sourceUrl: "https://neo4j.com/event/agntcon-mcpcon-japan/",
        sourceLabel: "neo4j.com",
      },
      {
        id: "neo4j-graphtalk-finserv-nordics",
        name: "GraphTalk FinServ Nordics",
        dateLabel: "Sep 16",
        sortDate: "2026-09-16",
        format: "in-person",
        location: "Hotel At Six, Stockholm, Sweden",
        description:
          "Financial-services GraphTalk on fraud, risk, and graph-backed decisioning for data and risk leaders.",
        status: "confirmed",
        sourceUrl: "https://neo4j.com/event/graphtalk-finserv-nordics/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag"],
      },
      {
        id: "neo4j-ai-builders-amsterdam",
        name: "AI Builders Amsterdam",
        dateLabel: "Sep 16",
        sortDate: "2026-09-16",
        format: "in-person",
        location: "Amsterdam, Netherlands",
        description:
          "Community meetup listed by Neo4j on AI dev tools, agent frameworks, and RAG — builders sharing practical stack notes.",
        status: "confirmed",
        sourceUrl: "https://neo4j.com/event/ai-builders-amsterdam-2/",
        sourceLabel: "neo4j.com",
        topics: ["rag"],
      },
      {
        id: "neo4j-agntcon-mcpcon-europe",
        name: "AGNTCon + MCPCon Europe",
        dateLabel: "Sep 17–18",
        sortDate: "2026-09-17",
        format: "in-person",
        location: "Europe — venue TBA (confirm on neo4j.com/event/agntcon-mcpcon-europe)",
        description:
          "European AGNTCon + MCPCon stop listed by Neo4j — agent architectures, infrastructure, and MCP tooling.",
        status: "check-source",
        sourceUrl: "https://neo4j.com/event/agntcon-mcpcon-europe/",
        sourceLabel: "neo4j.com",
      },
      {
        id: "neo4j-graphsummit-nyc",
        name: "GraphSummit NYC",
        dateLabel: "Sep 17",
        sortDate: "2026-09-17",
        format: "in-person",
        location: "New York, NY",
        description:
          "Flagship regional GraphRAG/AI-ready-data conference — knowledge layer for enterprise AI context, memory, and reasoning (neo4j.com/events lists Sep 17 as of 2026-08-13).",
        status: "confirmed",
        sourceUrl: "https://neo4j.com/event/graphsummit-new-york-3/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag", "agent-memory"],
      },
      {
        id: "neo4j-graph-intelligence-cincinnati",
        name: "Neo4j Graph Intelligence Hands-On Workshop — Cincinnati",
        dateLabel: "Sep 24",
        sortDate: "2026-09-24",
        format: "in-person",
        location: "Oakley Taproom, Cincinnati, OH",
        description:
          "In-person workshop on integrating GraphRAG into GenAI solutions — accuracy, relevance, and explainability for production systems.",
        status: "confirmed",
        sourceUrl:
          "https://neo4j.com/event/neo4j-graph-intelligence-hands-on-workshop-cincinnati/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag", "rag"],
      },
      {
        id: "neo4j-foundry-workshop-chicago",
        name: "AI Hands-On Workshop with Neo4j and Microsoft Foundry — Chicago",
        dateLabel: "Oct 1",
        sortDate: "2026-10-01",
        format: "in-person",
        location: "Aon Center, Chicago, IL",
        description:
          "Hands-on GraphRAG pipeline workshop on Azure — Neo4j Aura integrated with Microsoft Foundry.",
        status: "confirmed",
        sourceUrl:
          "https://neo4j.com/event/ai-hands-on-workshop-with-neo4j-and-microsoft-foundry-chicago/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag"],
      },
      {
        id: "neo4j-gemini-workshop-sunnyvale",
        name: "AI Hands-On Workshop with Neo4j and Google Gemini — Sunnyvale",
        dateLabel: "Oct 1",
        sortDate: "2026-10-01",
        format: "in-person",
        location: "Google Building MP3, 1170 Bordeaux Dr, Sunnyvale, CA",
        description:
          "Hands-on Bay Area workshop pairing Neo4j with Google Cloud Gemini Enterprise — load a real dataset, then build AI agents that use a knowledge graph (listed on neo4j.com/events as of 2026-08-13).",
        status: "confirmed",
        sourceUrl:
          "https://neo4j.com/event/ai-hands-on-workshop-with-neo4j-and-google-gemini-sunnyvale/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag", "agent-memory"],
      },
      {
        id: "neo4j-graphsummit-london",
        name: "GraphSummit London",
        dateLabel: "Oct 6",
        sortDate: "2026-10-06",
        format: "in-person",
        location: "88 Wood Street, London",
        description: '"Build With Graph and GenAI" — part of the GraphSummit 2026 tour.',
        status: "confirmed",
        sourceUrl: "https://neo4j.com/event/graphsummit-london-4/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag", "agent-memory"],
      },
      {
        id: "neo4j-graphtalk-madrid",
        name: "GraphTalk Madrid",
        dateLabel: "Oct 8",
        sortDate: "2026-10-08",
        format: "in-person",
        location: "Comet Retiro, Madrid, Spain",
        description:
          "Neo4j GraphTalk on graph databases for GenAI — use cases, graph modeling, preparing data for AI, and ecosystem updates.",
        status: "confirmed",
        sourceUrl:
          "https://neo4j.com/event/registrate-al-graphtalk-madrid-bases-de-datos-de-grafos-para-genia/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag"],
      },
      {
        id: "neo4j-vienna-demo-to-production",
        name: "From Demo to Production — Grounding AI with Knowledge Graphs (Vienna)",
        dateLabel: "Oct 29",
        sortDate: "2026-10-29",
        format: "in-person",
        location: "Vienna, Austria",
        description:
          "Neo4j session on grounding production AI with knowledge graphs for transparency and trust over interconnected data.",
        status: "confirmed",
        sourceUrl:
          "https://neo4j.com/event/vienna-from-demo-to-production-deploying-ai-responsibly-in-a-complex-world/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag"],
      },
      {
        id: "neo4j-virtual-workshop-genai-fundamentals",
        name: "Neo4j Virtual Workshop: Generative AI Fundamentals with Neo4j",
        dateLabel: "Nov 4",
        sortDate: "2026-11-04",
        format: "virtual",
        description:
          "Hands-on virtual workshop on grounding GenAI with knowledge graphs — GraphRAG patterns for more accurate, explainable enterprise AI apps.",
        status: "confirmed",
        sourceUrl:
          "https://neo4j.com/event/neo4j-virtual-workshop-generative-ai-fundamentals-with-neo4j_nov4/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag"],
      },
      {
        id: "neo4j-nodes-2026",
        name: "NODES 2026",
        dateLabel: "Nov 12",
        sortDate: "2026-11-12",
        format: "virtual",
        description: 'Neo4j\'s flagship 24-hour global developer conference — "Engineering Better Intelligence," with sessions on AI engineering, multi-agent workflows, and GraphRAG.',
        status: "confirmed",
        sourceUrl: "https://neo4j.com/nodes/",
        sourceLabel: "neo4j.com/nodes",
        topics: ["graphrag", "agent-memory"],
      },
      {
        id: "neo4j-genai-workshop-reply-aws",
        name: "Neo4j GenAI Workshop with Reply and AWS",
        dateLabel: "Nov 18",
        sortDate: "2026-11-18",
        format: "hybrid",
        location: "Munich / online",
        description:
          "Hands-on session with Neo4j, Reply, and AWS on building context-driven GenAI applications with graph technology.",
        status: "confirmed",
        sourceUrl: "https://neo4j.com/event/neo4j-genai-workshop-with-reply-and-aws_16sept/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag"],
      },
      {
        id: "neo4j-virtual-workshop-graph-reasoning",
        name: "Neo4j Virtual Workshop: Graph Reasoning with Neo4j Virtual Graph",
        dateLabel: "Nov 25",
        sortDate: "2026-11-25",
        format: "virtual",
        description:
          "Virtual workshop on querying warehouse data (Snowflake, Databricks, BigQuery) as a graph via Neo4j Virtual Graph — graph reasoning without data movement.",
        status: "confirmed",
        sourceUrl:
          "https://neo4j.com/event/neo4j-virtual-workshop-graph-reasoning-with-neo4j-virtual-graph_nov25/",
        sourceLabel: "neo4j.com",
        topics: ["graphrag"],
      },
    ],
  },
  {
    id: "langchain",
    company: "LangChain",
    category: "Orchestration framework",
    homepageUrl: "https://www.langchain.com/events",
    events: [
      {
        id: "langchain-ny-meetup-agent-context",
        name: "LangChain NY Meetup — LLM Wikis and Managing Agent Context",
        dateLabel: "Aug 13",
        sortDate: "2026-08-13",
        format: "in-person",
        location: "New York, NY",
        description:
          "NYC community meetup on LLM wikis and managing agent context — direct overlap with agent-memory patterns.",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
        topics: ["agent-memory"],
      },
      {
        id: "langchain-langsmith-customer-ama",
        name: "Build More with LangSmith: Customer AMA",
        dateLabel: "Aug 19",
        sortDate: "2026-08-19",
        format: "virtual",
        description:
          "Virtual LangSmith customer AMA — product Q&A for teams building and evaluating agents.",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
      {
        id: "langchain-automating-eval-environment",
        name: "Towards Automating Eval & Environment Engineering",
        dateLabel: "Aug 20",
        sortDate: "2026-08-20",
        format: "virtual",
        description:
          "Virtual session on automating agent evaluation and environment engineering — listed on langchain.com/events.",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
      {
        id: "langchain-evaluate-voice-agents",
        name: "How to Evaluate Voice Agents: Execution, Outcomes, and Experience",
        dateLabel: "Aug 26",
        sortDate: "2026-08-26",
        format: "virtual",
        description:
          "Virtual session on evaluating voice agents across execution quality, outcomes, and user experience.",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
      {
        id: "langsmith-roadshow-silicon-valley",
        name: "LangSmith Roadshow — Silicon Valley",
        dateLabel: "Aug 27",
        sortDate: "2026-08-27",
        format: "in-person",
        location: "Silicon Valley, CA",
        description: "Product roadshow stop for LangSmith.",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
      {
        id: "langchain-hamburg-meetup",
        name: "LangChain Meetup — Building Great Agents (Hamburg)",
        dateLabel: "Sep 3",
        sortDate: "2026-09-03",
        format: "in-person",
        location: "Hamburg, Germany",
        description: "Hamburg community meetup on building production agents — listed on langchain.com/events.",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
      {
        id: "langchain-interrupt-nyc",
        name: "Interrupt NYC",
        dateLabel: "Sep 24",
        sortDate: "2026-09-24",
        format: "in-person",
        location: "New York, NY",
        description: "LangChain Interrupt conference — NYC fall edition listed on langchain.com/events.",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
      {
        id: "langsmith-roadshow-boston",
        name: "LangSmith Roadshow — Boston",
        dateLabel: "Sep 29",
        sortDate: "2026-09-29",
        format: "in-person",
        location: "Boston, MA",
        description: "Product roadshow stop for LangSmith.",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
      {
        id: "langsmith-roadshow-los-angeles",
        name: "LangSmith Roadshow — Los Angeles",
        dateLabel: "Oct 1",
        sortDate: "2026-10-01",
        format: "in-person",
        location: "Los Angeles, CA",
        description:
          "Product roadshow stop for LangSmith — Building Agents with Agents (listed on langchain.com/events as of 2026-08-13).",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
      {
        id: "langchain-world-summit-ai",
        name: "LangChain @ World Summit AI",
        dateLabel: "Oct 7",
        sortDate: "2026-10-07",
        format: "in-person",
        location: "Amsterdam",
        description: "LangChain presence at World Summit AI.",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
      {
        id: "langchain-interrupt-london",
        name: "Interrupt London",
        dateLabel: "Oct 13",
        sortDate: "2026-10-13",
        format: "in-person",
        location: "London, UK",
        description: "LangChain Interrupt conference — London fall edition listed on langchain.com/events.",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
      {
        id: "langchain-reinvent",
        name: "LangChain @ AWS re:Invent",
        dateLabel: "Nov 30",
        sortDate: "2026-11-30",
        format: "in-person",
        location: "Las Vegas, NV",
        description: "LangChain presence at AWS re:Invent.",
        status: "confirmed",
        sourceUrl: "https://www.langchain.com/events",
        sourceLabel: "langchain.com",
      },
    ],
  },
  {
    id: "mongodb",
    company: "MongoDB",
    category: "Atlas Vector Search",
    homepageUrl: "https://www.mongodb.com/resources/webinars",
    events: [
      {
        id: "mongodb-observability-ai-agents",
        name: "Observability for AI Agents",
        dateLabel: "Sep 9, 11am–1pm ET",
        sortDate: "2026-09-09",
        format: "virtual",
        description:
          "Webinar on observing why agents behave the way they do in production — beyond uptime monitoring into agent-behavior diagnostics.",
        status: "confirmed",
        sourceUrl: "https://www.mongodb.com/resources/webinars",
        sourceLabel: "mongodb.com",
      },
      {
        id: "mongodb-vector-search-fundamentals-sgt",
        name: "Vector Search Fundamentals (SGT)",
        dateLabel: "Sep 10, 2pm SGT",
        sortDate: "2026-09-10",
        format: "virtual",
        description:
          "APAC-timezone webinar on MongoDB Vector Search for meaning-based retrieval — embeddings, indexing, and vector search fundamentals.",
        status: "confirmed",
        sourceUrl: "https://www.mongodb.com/resources/webinars",
        sourceLabel: "mongodb.com",
        topics: ["vector-db", "rag"],
      },
      {
        id: "mongodb-governance-ai-agents",
        name: "Governance for AI Agents",
        dateLabel: "Sep 16, 11am–1pm ET",
        sortDate: "2026-09-16",
        format: "virtual",
        description:
          "Webinar on governing what agents are allowed to do — permissions, accountability, and control points when agents access data and tools.",
        status: "confirmed",
        sourceUrl: "https://www.mongodb.com/resources/webinars",
        sourceLabel: "mongodb.com",
      },
      {
        id: "mongodb-rag-webinar-sgt",
        name: "RAG with MongoDB (SGT)",
        dateLabel: "Sep 17, 2pm SGT",
        sortDate: "2026-09-17",
        format: "virtual",
        description:
          "APAC-timezone webinar on building retrieval-augmented generation apps with MongoDB — chunking, retrievers, and RAG architecture.",
        status: "confirmed",
        sourceUrl: "https://www.mongodb.com/resources/webinars",
        sourceLabel: "mongodb.com",
        topics: ["rag", "vector-db"],
      },
      {
        id: "mongodb-evaluating-agentic-platform",
        name: "Evaluating an Agentic AI Platform",
        dateLabel: "Sep 23, 11am–1pm ET",
        sortDate: "2026-09-23",
        format: "virtual",
        description:
          "Webinar on closing the demo-to-production gap for agent platforms — security review, cost control, and evaluation criteria.",
        status: "confirmed",
        sourceUrl: "https://www.mongodb.com/resources/webinars",
        sourceLabel: "mongodb.com",
      },
      {
        id: "mongodb-ai-agents-sgt",
        name: "AI Agents with MongoDB (SGT)",
        dateLabel: "Sep 24, 10am SGT",
        sortDate: "2026-09-24",
        format: "virtual",
        description:
          "APAC-timezone capstone webinar on building AI agents with MongoDB — tools, decision-making, and memory.",
        status: "confirmed",
        sourceUrl: "https://www.mongodb.com/resources/webinars",
        sourceLabel: "mongodb.com",
        topics: ["agent-memory"],
      },
      {
        id: "mongodb-vector-search-fundamentals",
        name: "Vector Search Fundamentals",
        dateLabel: "Oct 1, 11am ET",
        sortDate: "2026-10-01",
        format: "virtual",
        description:
          "Webinar on MongoDB Vector Search for meaning-based retrieval — indexing and vector search fundamentals.",
        status: "confirmed",
        sourceUrl: "https://www.mongodb.com/resources/webinars",
        sourceLabel: "mongodb.com",
        topics: ["vector-db", "rag"],
      },
      {
        id: "mongodb-vector-search-fundamentals-bst",
        name: "Vector Search Fundamentals (BST)",
        dateLabel: "Oct 6, 10am BST",
        sortDate: "2026-10-06",
        format: "virtual",
        description:
          "UK/EU-timezone webinar on MongoDB Vector Search for meaning-based retrieval — embeddings, indexing, and vector search fundamentals.",
        status: "confirmed",
        sourceUrl: "https://www.mongodb.com/resources/webinars",
        sourceLabel: "mongodb.com",
        topics: ["vector-db", "rag"],
      },
      {
        id: "mongodb-rag-webinar",
        name: "RAG with MongoDB",
        dateLabel: "Oct 8, 11am ET",
        sortDate: "2026-10-08",
        format: "virtual",
        description:
          "Webinar on building retrieval-augmented generation apps with MongoDB — chunking, retrievers, and RAG architecture.",
        status: "confirmed",
        sourceUrl: "https://www.mongodb.com/resources/webinars",
        sourceLabel: "mongodb.com",
        topics: ["rag", "vector-db"],
      },
      {
        id: "mongodb-rag-webinar-bst",
        name: "RAG with MongoDB (BST)",
        dateLabel: "Oct 13, 10am BST",
        sortDate: "2026-10-13",
        format: "virtual",
        description:
          "UK/EU-timezone webinar on building retrieval-augmented generation apps with MongoDB — chunking, retrievers, and RAG architecture.",
        status: "confirmed",
        sourceUrl: "https://www.mongodb.com/resources/webinars",
        sourceLabel: "mongodb.com",
        topics: ["rag", "vector-db"],
      },
      {
        id: "mongodb-ai-agents-oct",
        name: "AI Agents with MongoDB",
        dateLabel: "Oct 15, 11am ET",
        sortDate: "2026-10-15",
        format: "virtual",
        description:
          "Capstone webinar on building AI agents with MongoDB — tools, decision-making, and memory.",
        status: "confirmed",
        sourceUrl: "https://www.mongodb.com/resources/webinars",
        sourceLabel: "mongodb.com",
        topics: ["agent-memory"],
      },
      {
        id: "mongodb-ai-agents-bst",
        name: "AI Agents with MongoDB (BST)",
        dateLabel: "Oct 20, 10am BST",
        sortDate: "2026-10-20",
        format: "virtual",
        description:
          "UK/EU-timezone capstone webinar on building AI agents with MongoDB — tools, decision-making, and memory.",
        status: "confirmed",
        sourceUrl: "https://www.mongodb.com/resources/webinars",
        sourceLabel: "mongodb.com",
        topics: ["agent-memory"],
      },
    ],
    watchNote:
      "MongoDB.local's flagship regional conference series didn't have confirmed Jul–Dec city dates at research time — check mongodb.com/events directly. Jul 22–23 Vector Search / AI Agents / Atlas+Confluent and Jul 29 AI System Design sessions have passed. Aug 4 AI Coding webinar pruned after Pacific day passed. Observability / Governance / Evaluating Agentic AI Platform webinar series (Sep 9 / 16 / 23 ET) — leave topics unset (ops/governance, not retrieval). APAC (SGT) Sep 10 / 17 / 24, Oct ET, and Oct BST (Oct 6 / 13 / 20) Vector Search / RAG / AI Agents series still confirmed as of 2026-08-13. Persistent Context Sprint hackathon (Aug 13, SF) tracked in events.ts as a Bay Area builder listing.",
  },
  {
    id: "redis",
    company: "Redis",
    category: "Vector search / RAG",
    homepageUrl: "https://redis.io/events/",
    events: [
      {
        id: "redis-real-time-context-engine",
        name: "Real-time Context Engine: RAG, Memory & Agentic Infra",
        dateLabel: "Aug 13",
        sortDate: "2026-08-13",
        format: "virtual",
        description:
          "Webinar on RAG, agent memory, and agentic infrastructure using Redis — direct overlap with HydraDB's territory.",
        status: "confirmed",
        sourceUrl:
          "https://redis.io/resources/videos/real-time-context-engine-rag-memory-agentic-infra/",
        sourceLabel: "redis.io",
        topics: ["rag", "agent-memory"],
      },
      {
        id: "redis-office-hours-context-engineering",
        name: "Office Hours: Context Engineering",
        dateLabel: "Sep 9",
        sortDate: "2026-09-09",
        format: "virtual",
        description:
          "Redis office hours on context engineering for agents — agent memory and retrieval context patterns (dateNew / icsStart Sep 9, 9:00 AM PT as of 2026-08-13; previously listed Aug 20).",
        status: "confirmed",
        sourceUrl: "https://redis.io/resources/videos/office-hours-context-engineering/",
        sourceLabel: "redis.io",
        topics: ["agent-memory"],
      },
    ],
  },
  {
    id: "zilliz",
    company: "Zilliz / Milvus",
    category: "Vector database",
    homepageUrl: "https://zilliz.com/event",
    events: [],
    watchNote:
      "BYOC webinar (Jul 29) pruned after Pacific day passed (isPast:true on zilliz.com). Unstructured Data Meetup series still has no confirmed forward dates on zilliz.com/event as of 2026-08-13. Check zilliz.com/community/unstructured-data-meetup directly.",
  },
  {
    id: "qdrant",
    company: "Qdrant",
    category: "Vector database",
    homepageUrl: "https://qdrant.tech/events/",
    events: [
      {
        id: "qdrant-sf-community-meetup",
        name: "SF Community Meetup: AI Debate Night",
        dateLabel: "Aug 25",
        sortDate: "2026-08-25",
        format: "in-person",
        location: "San Francisco, CA",
        description:
          "Save-the-date SF community meetup listed as an AI debate night for engineers and researchers — confirm agenda/venue closer to the day.",
        status: "check-source",
        sourceUrl: "https://qdrant.tech/events/",
        sourceLabel: "qdrant.tech",
      },
      {
        id: "qdrant-hard-negatives-nyc",
        name: "Hard Negatives: AI Engineers Debate & Game Night",
        dateLabel: "Aug 26",
        sortDate: "2026-08-26",
        format: "in-person",
        location: "Sugar Mouse NYC, New York, NY",
        description:
          "Debate/game night for AI engineers (provocations include “RAG is dead”) — community mixer with retrieval themes, not a technical deep dive.",
        status: "confirmed",
        sourceUrl: "https://qdrant.tech/events/",
        sourceLabel: "qdrant.tech",
      },
      {
        id: "qdrant-berlin-community-meetup",
        name: "Qdrant Berlin Community Meetup",
        dateLabel: "Sep 16",
        sortDate: "2026-09-16",
        format: "in-person",
        location: "Berlin, Germany",
        description:
          "Save-the-date evening at Qdrant HQ — engineering conversations and practical demos.",
        status: "check-source",
        sourceUrl: "https://qdrant.tech/events/",
        sourceLabel: "qdrant.tech",
        topics: ["vector-db"],
      },
    ],
    watchNote:
      "Upcoming dated list refreshed from qdrant.tech/events (2026-08-13). Engineering Self-Improving AI Systems (Jul 29, AWS Loft SF) pruned after Pacific day passed. SF Aug 25 title still “AI Debate Night” and Berlin Sep 16 remain save-the-dates — confirm venue/agenda closer to the day. August Discord Office Hours (Aug 20) and OpenAI Codex Fast Hacks Tokyo (Aug 27) skipped. Vector Space Meetup / Day already ran Jun 11.",
  },
  {
    id: "weaviate",
    company: "Weaviate",
    category: "Vector database",
    homepageUrl: "https://weaviate.io/community/events",
    events: [],
    watchNote:
      "Weaviate's own events page showed no scheduled events at research time (2026-08-13): \"Sorry, there are no events right now.\" SF and NYC meetup chapters exist but had no dated 2026 sessions listed. Check weaviate.io/community/events and meetup.com/Weaviate-San-Francisco.",
  },
  {
    id: "chroma",
    company: "Chroma",
    category: "Vector database",
    homepageUrl: "https://www.trychroma.com",
    events: [],
    watchNote:
      "No public events calendar found for Chroma at research time. Check trychroma.com and @trychroma on X directly.",
  },
  {
    id: "llamaindex",
    company: "LlamaIndex",
    category: "Orchestration framework",
    homepageUrl: "https://www.llamaindex.ai/blog",
    events: [],
    watchNote:
      "No confirmed dated Jul–Dec 2026 events found — LlamaIndex's most recent confirmed item was a Jun 30 webinar, just before this window. Their blog/newsletter is the primary events channel; check llamaindex.ai/blog monthly. Re-checked 2026-08-13.",
  },
  {
    id: "elastic",
    company: "Elastic",
    category: "Vector search / RAG",
    homepageUrl: "https://events.elastic.co",
    events: [],
    watchNote:
      'An open-ended "Blogathon" community content campaign is running (not a single-date event). No single confirmed live event date found in-window — events.elastic.co blocked automated fetch, so a manual check will likely surface more.',
  },
  {
    id: "mem0",
    company: "Mem0",
    category: "Agent memory layer",
    homepageUrl: "https://mem0.ai",
    events: [
      {
        id: "mem0-context-corner-aug14",
        name: "Context Corner: A Lunch Series for Developers",
        dateLabel: "Aug 14",
        sortDate: "2026-08-14",
        format: "in-person",
        location: "San Francisco, CA",
        description:
          "Small Mem0-hosted lunch for developers on real challenges with context, memory, and agents — second Context Corner session (extended runtime after the first).",
        status: "confirmed",
        sourceUrl: "https://luma.com/mem0-a82x",
        sourceLabel: "luma.com/mem0",
        topics: ["agent-memory"],
      },
      {
        id: "mem0-memory-for-llms-aug27",
        name: "Memory for LLMs",
        dateLabel: "Aug 27",
        sortDate: "2026-08-27",
        format: "in-person",
        location: "Sunnyvale, CA",
        description:
          "Evening technical talks on LLM memory — persistent, context-aware applications beyond the context window (listed on luma.com/mem0 as of 2026-08-13).",
        status: "confirmed",
        sourceUrl: "https://luma.com/ey4era2u",
        sourceLabel: "luma.com/mem0",
        topics: ["agent-memory"],
      },
    ],
    watchNote:
      "Re-checked luma.com/mem0 (cal-URD2cnrxGOxlBjx) on 2026-08-13: Context Corner lunch still Aug 14; new Memory for LLMs evening Aug 27 in Sunnyvale (tracked above). Jog Your Memory run club + matcha (Aug 17) and Consumer AI founders mixer (Aug 13) still skipped as social. Re-read the calendar after each lunch cadence.",
  },
  {
    id: "supermemory",
    company: "Supermemory",
    category: "Memory + RAG API",
    homepageUrl: "https://supermemory.ai",
    events: [],
    watchNote:
      "No dedicated events page — Supermemory (memory + RAG hybrid context API) surfaces events via blog and X. The localhost:6767 hackathon deadline (Jul 17) has passed; no new dated Jul–Dec 2026 events found on blog.supermemory.ai as of 2026-08-13. Check blog.supermemory.ai and @supermemoryai.",
  },
];
